const content = {
    uz: {
        home: "Uy",
        explore: "O'rganing",
        notification: "Bildirishnoma",
        messages: "Xabarlar",
        bookmarks: "Xatcho'plar",
        lists: "Ro'yxatlar",
        profile: "Profil",
        more: "Ko'proq",
        trend: "Siz uchun trendlar",
        trending: "Germaniyada trend",
        revalution: "Qayta baholash",
        like: "Sizga yoqishi mumkin",
        follow: "Kuzatish",
        paragraf: "Xizmat ko'rsatish shartlari Maxfiylik siyosati Cookie siyosati",
        paragraf2: " Bosib chiqarish Reklama haqida ma 'lumot Ko 'proq ···©2021 Twitter,Inc.",
        koproq: "Ko'proq ko'rsatish",
        heppening: "Nimalar bo'lyapti",
        search: "Twitter qidirish",
    },
    ru: {
        home: "Дом",
        explore: "Исследовать",
        notification: "Уведомления",
        messages: "Сообщения",
        bookmarks: "Закладки",
        lists: "Списки",
        profile: "Профиль",
        more: "Более",
        trend: "Тенденции для вас",
        trending: "тренд в Германии",
        revalution: "Переоценка",
        like: "Вам может понравиться",
        follow: "Отслеживание",
        paragraf: "Условия использования Политика конфиденциальности Политика использования файлов cookie",
        paragraf2: " Печатная рекламная информация Подробнее ··· © 2021 Twitter, Inc",
        koproq: "Показать еще",
        heppening: "Что творится",
        search: "Искать в Twitter",
    },
    en: {
        home: "Home",
        explore: "Explore",
        notification: "Notification",
        messages: "Messages",
        bookmarks: "Bookmarks",
        lists: "Lists",
        profile: "Profile",
        more: "More",
        trend: "Trends for you",
        trending: "Trending in Germany",
        revalution: "Revolution",
        like: "You might like",
        follow: "Follow",
        paragraf: "Terms of Service Privacy Policy Cookie Policy",
        paragraf2: "Imprint Ads Info More ··· © 2021 Twitter, Inc.",
        koproq: "Show more",
        heppening: "What’s happening?",
        search: "Search Twitter",
    }
};

export default content;